# Generated by Django 5.2.14 on 2026-05-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nama Makanan')),
                ('name_lower', models.CharField(editable=False, max_length=200)),
                ('source', models.CharField(default='DKBM-Nutrisurvey', max_length=100, verbose_name='Sumber Data')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Makanan Kustom')),
            ],
            options={
                'verbose_name': 'Makanan',
                'verbose_name_plural': 'Makanan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_kcal', models.FloatField(blank=True, null=True, verbose_name='Energi (kkal)')),
                ('energy_kj', models.FloatField(blank=True, null=True, verbose_name='Energi (kJ)')),
                ('protein_g', models.FloatField(blank=True, null=True, verbose_name='Protein (g)')),
                ('fat_g', models.FloatField(blank=True, null=True, verbose_name='Lemak (g)')),
                ('carbohydrate_g', models.FloatField(blank=True, null=True, verbose_name='Karbohidrat (g)')),
                ('fiber_g', models.FloatField(blank=True, null=True, verbose_name='Serat (g)')),
                ('calcium_mg', models.FloatField(blank=True, null=True, verbose_name='Kalsium (mg)')),
                ('iron_mg', models.FloatField(blank=True, null=True, verbose_name='Besi (mg)')),
                ('magnesium_mg', models.FloatField(blank=True, null=True, verbose_name='Magnesium (mg)')),
                ('thiamin_mg', models.FloatField(blank=True, null=True, verbose_name='Tiamin (mg)')),
                ('riboflavin_mg', models.FloatField(blank=True, null=True, verbose_name='Riboflavin (mg)')),
                ('zinc_mg', models.FloatField(blank=True, null=True, verbose_name='Zinc (mg)')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutritionfact', to='foods.food')),
            ],
            options={
                'verbose_name': 'Nilai Gizi',
                'verbose_name_plural': 'Nilai Gizi',
            },
        ),
    ]
