# Generated by Django 5.2.14 on 2026-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionfact',
            name='energy_kj',
        ),
        migrations.AddField(
            model_name='food',
            name='bdd_pct',
            field=models.FloatField(default=100.0, verbose_name='BDD (%)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='beta_carotene_mcg',
            field=models.FloatField(blank=True, null=True, verbose_name='Beta-Karoten (mcg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='copper_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Tembaga (mg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='niacin_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Niasin (mg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='phosphorus_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Fosfor (mg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='potassium_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Kalium (mg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='retinol_mcg',
            field=models.FloatField(blank=True, null=True, verbose_name='Retinol (mcg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='sodium_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Natrium (mg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='vitamin_c_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin C (mg)'),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='water_g',
            field=models.FloatField(blank=True, null=True, verbose_name='Air (g)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='source',
            field=models.CharField(default='TKPI-2020', max_length=100, verbose_name='Sumber Data'),
        ),
        migrations.AlterField(
            model_name='nutritionfact',
            name='zinc_mg',
            field=models.FloatField(blank=True, null=True, verbose_name='Seng (mg)'),
        ),
    ]
