# Generated by Django 5.2.14 on 2026-05-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(verbose_name='Berat Badan (kg)')),
                ('height_cm', models.FloatField(verbose_name='Tinggi Badan (cm)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imt_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catatan IMT',
                'verbose_name_plural': 'Catatan IMT',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Pria'), ('F', 'Wanita')], default='M', max_length=1)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Tidak Aktif (kerja kantoran, tidak olahraga)'), ('light', 'Ringan (olahraga 1-3x/minggu)'), ('moderate', 'Sedang (olahraga 3-5x/minggu)'), ('active', 'Aktif (olahraga intensif 6-7x/minggu)'), ('very_active', 'Sangat Aktif (atlet / kerja fisik berat)')], default='sedentary', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Pengguna',
                'verbose_name_plural': 'Profil Pengguna',
            },
        ),
    ]
