# Generated by Django 5.2.14 on 2026-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Pengguna Biasa'), ('ahli_gizi', 'Ahli Gizi')], default='user', max_length=20, verbose_name='Role'),
        ),
    ]
