# Generated by Django 5.2.14 on 2026-05-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Harian',
                'verbose_name_plural': 'Log Harian',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Kustom')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Sarapan'), ('lunch', 'Makan Siang'), ('dinner', 'Makan Malam'), ('snack', 'Camilan')], max_length=20, verbose_name='Waktu Makan')),
                ('amount_g', models.FloatField(verbose_name='Jumlah (gram)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.food')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tracking.dailylog')),
            ],
            options={
                'verbose_name': 'Entri Makanan',
                'verbose_name_plural': 'Entri Makanan',
                'ordering': ['meal_type', 'created_at'],
            },
        ),
    ]
